/**
 * Demo data service - provides sample companies for public demo mode
 * This allows visitors to explore the heat map without signing in
 */

export const DEMO_COMPANIES = [
  {
    id: 1,
    name: "Google",
    industry: "Technology",
    headquartersCity: "Mountain View",
    headquartersState: "CA",
    sizeRange: "10000+",
    aggregateScore: {
      overallRating: 4.6,
      workLifeBalance: 4.2,
      compensationBenefits: 4.8,
      careerOpportunities: 4.7,
      cultureValues: 4.5,
      seniorManagement: 4.3,
    },
    logoUrl: "https://www.gstatic.com/images/branding/product/1x/googleg_40dp.png",
    turnoverRate: 9.5,
    avgTenure: 4.0,
  },
  {
    id: 2,
    name: "Microsoft",
    industry: "Technology",
    headquartersCity: "Redmond",
    headquartersState: "WA",
    sizeRange: "10000+",
    aggregateScore: {
      overallRating: 4.4,
      workLifeBalance: 4.1,
      compensationBenefits: 4.6,
      careerOpportunities: 4.5,
      cultureValues: 4.3,
      seniorManagement: 4.2,
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Microsoft_logo.svg/200px-Microsoft_logo.svg.png",
    turnoverRate: 11.2,
    avgTenure: 3.9,
    },
  },
  {
    id: 3,
    name: "Apple",
    industry: "Technology",
    headquartersCity: "Cupertino",
    headquartersState: "CA",
    sizeRange: "10000+",
    aggregateScore: {
      overallRating: 4.3,
      workLifeBalance: 3.8,
      compensationBenefits: 4.7,
      careerOpportunities: 4.4,
      cultureValues: 4.2,
      seniorManagement: 4.1,
    logoUrl: "https://www.apple.com/ac/structured-data/images/open_graph_logo.png",
    turnoverRate: 13.8,
    avgTenure: 3.6,
    },
  },
  {
    id: 4,
    name: "Amazon",
    industry: "Technology",
    headquartersCity: "Seattle",
    headquartersState: "WA",
    sizeRange: "10000+",
    aggregateScore: {
      overallRating: 3.9,
      workLifeBalance: 3.4,
      compensationBenefits: 4.3,
      careerOpportunities: 4.2,
      cultureValues: 3.8,
      seniorManagement: 3.7,
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Amazon_logo.svg/200px-Amazon_logo.svg.png",
    turnoverRate: 22.5,
    avgTenure: 2.8,
    },
  },
  {
    id: 5,
    name: "Meta",
    industry: "Technology",
    headquartersCity: "Menlo Park",
    headquartersState: "CA",
    sizeRange: "10000+",
    aggregateScore: {
      overallRating: 4.1,
      workLifeBalance: 3.9,
      compensationBenefits: 4.8,
      careerOpportunities: 4.3,
      cultureValues: 4.0,
      seniorManagement: 3.9,
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Meta_Platforms_Inc_logo.svg/200px-Meta_Platforms_Inc_logo.svg.png",
    turnoverRate: 18.3,
    avgTenure: 3.2,
    },
  },
  {
    id: 6,
    name: "Tesla",
    industry: "Technology",
    headquartersCity: "Austin",
    headquartersState: "TX",
    sizeRange: "10000+",
    aggregateScore: {
      overallRating: 3.7,
      workLifeBalance: 3.2,
      compensationBenefits: 4.2,
      careerOpportunities: 4.1,
      cultureValues: 3.6,
      seniorManagement: 3.5,
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Tesla_logo.png/200px-Tesla_logo.png",
    turnoverRate: 28.5,
    avgTenure: 2.1,
    },
  },
  {
    id: 7,
    name: "JPMorgan Chase",
    industry: "Finance",
    headquartersCity: "New York",
    headquartersState: "NY",
    sizeRange: "10000+",
    aggregateScore: {
      overallRating: 4.2,
      workLifeBalance: 3.8,
      compensationBenefits: 4.6,
      careerOpportunities: 4.3,
      cultureValues: 4.1,
      seniorManagement: 4.0,
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/JPMorgan_Chase_Logo_2008_1.svg/200px-JPMorgan_Chase_Logo_2008_1.svg.png",
    turnoverRate: 14.5,
    avgTenure: 3.5,
    },
  },
  {
    id: 8,
    name: "Goldman Sachs",
    industry: "Finance",
    headquartersCity: "New York",
    headquartersState: "NY",
    sizeRange: "10000+",
    aggregateScore: {
      overallRating: 4.0,
      workLifeBalance: 3.5,
      compensationBenefits: 4.7,
      careerOpportunities: 4.2,
      cultureValues: 3.9,
      seniorManagement: 3.8,
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Goldman_Sachs.svg/200px-Goldman_Sachs.svg.png",
    turnoverRate: 18.2,
    avgTenure: 3.2,
    },
  },
  {
    id: 9,
    name: "Morgan Stanley",
    industry: "Finance",
    headquartersCity: "New York",
    headquartersState: "NY",
    sizeRange: "10000+",
    aggregateScore: {
      overallRating: 4.1,
      workLifeBalance: 3.6,
      compensationBenefits: 4.6,
      careerOpportunities: 4.2,
      cultureValues: 4.0,
      seniorManagement: 3.9,
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Morgan_Stanley_logo.svg/200px-Morgan_Stanley_logo.svg.png",
    turnoverRate: 16.1,
    avgTenure: 3.4,
    },
  },
  {
    id: 10,
    name: "Bank of America",
    industry: "Finance",
    headquartersCity: "Charlotte",
    headquartersState: "NC",
    sizeRange: "10000+",
    aggregateScore: {
      overallRating: 3.9,
      workLifeBalance: 3.7,
      compensationBenefits: 4.3,
      careerOpportunities: 4.0,
      cultureValues: 3.8,
      seniorManagement: 3.7,
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/BofA_logo.svg/200px-BofA_logo.svg.png",
    turnoverRate: 19.8,
    avgTenure: 3.0,
    },
  },
  {
    id: 11,
    name: "Pfizer",
    industry: "Healthcare",
    headquartersCity: "New York",
    headquartersState: "NY",
    sizeRange: "10000+",
    aggregateScore: {
      overallRating: 4.3,
      workLifeBalance: 4.1,
      compensationBenefits: 4.5,
      careerOpportunities: 4.2,
      cultureValues: 4.2,
      seniorManagement: 4.1,
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Pfizer_logo.svg/200px-Pfizer_logo.svg.png",
    turnoverRate: 11.8,
    avgTenure: 3.8,
    },
  },
  {
    id: 12,
    name: "Johnson & Johnson",
    industry: "Healthcare",
    headquartersCity: "New Brunswick",
    headquartersState: "NJ",
    sizeRange: "10000+",
    aggregateScore: {
      overallRating: 4.4,
      workLifeBalance: 4.2,
      compensationBenefits: 4.6,
      careerOpportunities: 4.3,
      cultureValues: 4.3,
      seniorManagement: 4.2,
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Johnson_%26_Johnson_logo.svg/200px-Johnson_%26_Johnson_logo.svg.png",
    turnoverRate: 10.9,
    avgTenure: 3.9,
    },
  },
  {
    id: 13,
    name: "Moderna",
    industry: "Healthcare",
    headquartersCity: "Cambridge",
    headquartersState: "MA",
    sizeRange: "1000-10000",
    aggregateScore: {
      overallRating: 4.2,
      workLifeBalance: 4.0,
      compensationBenefits: 4.7,
      careerOpportunities: 4.4,
      cultureValues: 4.1,
      seniorManagement: 4.0,
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Moderna_2020_logo.svg/200px-Moderna_2020_logo.svg.png",
    turnoverRate: 15.6,
    avgTenure: 3.4,
    },
  },
  {
    id: 14,
    name: "Nvidia",
    industry: "Technology",
    headquartersCity: "Santa Clara",
    headquartersState: "CA",
    sizeRange: "10000+",
    aggregateScore: {
      overallRating: 4.5,
      workLifeBalance: 4.2,
      compensationBenefits: 4.8,
      careerOpportunities: 4.6,
      cultureValues: 4.4,
      seniorManagement: 4.3,
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Nvidia_logo.svg/200px-Nvidia_logo.svg.png",
    turnoverRate: 8.9,
    avgTenure: 4.1,
    },
  },
  {
    id: 15,
    name: "Intel",
    industry: "Technology",
    headquartersCity: "Santa Clara",
    headquartersState: "CA",
    sizeRange: "10000+",
    aggregateScore: {
      overallRating: 4.0,
      workLifeBalance: 3.9,
      compensationBenefits: 4.4,
      careerOpportunities: 4.1,
      cultureValues: 3.9,
      seniorManagement: 3.8,
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Intel_logo_%282020%2C_dark_blue%29.svg/200px-Intel_logo_%282020%2C_dark_blue%29.svg.png",
    turnoverRate: 14.2,
    avgTenure: 3.6,
    },
  },
  {
    id: 16,
    name: "Salesforce",
    industry: "Technology",
    headquartersCity: "San Francisco",
    headquartersState: "CA",
    sizeRange: "10000+",
    aggregateScore: {
      overallRating: 4.3,
      workLifeBalance: 4.1,
      compensationBenefits: 4.5,
      careerOpportunities: 4.3,
      cultureValues: 4.2,
      seniorManagement: 4.1,
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Salesforce.com_logo.svg/200px-Salesforce.com_logo.svg.png",
    turnoverRate: 15.3,
    avgTenure: 3.5,
    },
  },
  {
    id: 17,
    name: "Oracle",
    industry: "Technology",
    headquartersCity: "Austin",
    headquartersState: "TX",
    sizeRange: "10000+",
    aggregateScore: {
      overallRating: 3.8,
      workLifeBalance: 3.6,
      compensationBenefits: 4.3,
      careerOpportunities: 3.9,
      cultureValues: 3.7,
      seniorManagement: 3.6,
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Oracle_logo.svg/200px-Oracle_logo.svg.png",
    turnoverRate: 16.8,
    avgTenure: 3.3,
    },
  },
  {
    id: 18,
    name: "IBM",
    industry: "Technology",
    headquartersCity: "Armonk",
    headquartersState: "NY",
    sizeRange: "10000+",
    aggregateScore: {
      overallRating: 3.7,
      workLifeBalance: 3.8,
      compensationBenefits: 4.1,
      careerOpportunities: 3.8,
      cultureValues: 3.6,
      seniorManagement: 3.5,
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/IBM_logo.svg/200px-IBM_logo.svg.png",
    turnoverRate: 17.5,
    avgTenure: 3.2,
    },
  },
  {
    id: 19,
    name: "Accenture",
    industry: "Technology",
    headquartersCity: "New York",
    headquartersState: "NY",
    sizeRange: "10000+",
    aggregateScore: {
      overallRating: 4.1,
      workLifeBalance: 3.9,
      compensationBenefits: 4.3,
      careerOpportunities: 4.2,
      cultureValues: 4.0,
      seniorManagement: 3.9,
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Accenture.svg/200px-Accenture.svg.png",
    },
  },
  {
    id: 20,
    name: "Deloitte",
    industry: "Technology",
    headquartersCity: "New York",
    headquartersState: "NY",
    sizeRange: "10000+",
    aggregateScore: {
      overallRating: 4.0,
      workLifeBalance: 3.8,
      compensationBenefits: 4.2,
      careerOpportunities: 4.1,
      cultureValues: 3.9,
      seniorManagement: 3.8,
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Deloitte_Logo.svg/200px-Deloitte_Logo.svg.png",
    },
  },
  {
    id: 21,
    name: "Netflix",
    industry: "Technology",
    headquartersCity: "Los Gatos",
    headquartersState: "CA",
    sizeRange: "10000+",
    aggregateScore: {
      overallRating: 4.4,
      workLifeBalance: 4.3,
      compensationBenefits: 4.7,
      careerOpportunities: 4.4,
      cultureValues: 4.3,
      seniorManagement: 4.2,
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Netflix_logo.svg/200px-Netflix_logo.svg.png",
    turnoverRate: 12.1,
    avgTenure: 3.8,
    },
  },
  {
    id: 22,
    name: "Adobe",
    industry: "Technology",
    headquartersCity: "San Jose",
    headquartersState: "CA",
    sizeRange: "10000+",
    aggregateScore: {
      overallRating: 4.3,
      workLifeBalance: 4.2,
      compensationBenefits: 4.6,
      careerOpportunities: 4.3,
      cultureValues: 4.2,
      seniorManagement: 4.1,
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Adobe_Systems_logo_and_wordmark.svg/200px-Adobe_Systems_logo_and_wordmark.svg.png",
    turnoverRate: 10.5,
    avgTenure: 4.0,
    },
  },
  {
    id: 23,
    name: "Stripe",
    industry: "Technology",
    headquartersCity: "San Francisco",
    headquartersState: "CA",
    sizeRange: "1000-10000",
    aggregateScore: {
      overallRating: 4.5,
      workLifeBalance: 4.3,
      compensationBenefits: 4.8,
      careerOpportunities: 4.5,
      cultureValues: 4.4,
      seniorManagement: 4.3,
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Stripe_Logo%2C_revised_2016.svg/200px-Stripe_Logo%2C_revised_2016.svg.png",
    },
  },
  {
    id: 24,
    name: "Airbnb",
    industry: "Technology",
    headquartersCity: "San Francisco",
    headquartersState: "CA",
    sizeRange: "10000+",
    aggregateScore: {
      overallRating: 4.2,
      workLifeBalance: 4.0,
      compensationBenefits: 4.5,
      careerOpportunities: 4.2,
      cultureValues: 4.1,
      seniorManagement: 4.0,
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Airbnb_Logo_B%C3%A9lo.svg/200px-Airbnb_Logo_B%C3%A9lo.svg.png",
    },
  },
  {
    id: 25,
    name: "Uber",
    industry: "Technology",
    headquartersCity: "San Francisco",
    headquartersState: "CA",
    sizeRange: "10000+",
    aggregateScore: {
      overallRating: 3.8,
      workLifeBalance: 3.5,
      compensationBenefits: 4.4,
      careerOpportunities: 4.1,
      cultureValues: 3.7,
      seniorManagement: 3.6,
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Uber_logo_2018.svg/200px-Uber_logo_2018.svg.png",
    },
  },
  {
    id: 26,
    name: "Lyft",
    industry: "Technology",
    headquartersCity: "San Francisco",
    headquartersState: "CA",
    sizeRange: "1000-10000",
    aggregateScore: {
      overallRating: 3.9,
      workLifeBalance: 3.7,
      compensationBenefits: 4.3,
      careerOpportunities: 4.0,
      cultureValues: 3.8,
      seniorManagement: 3.7,
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Lyft_logo.svg/200px-Lyft_logo.svg.png",
    },
  },
  {
    id: 27,
    name: "Slack",
    industry: "Technology",
    headquartersCity: "San Francisco",
    headquartersState: "CA",
    sizeRange: "1000-10000",
    aggregateScore: {
      overallRating: 4.4,
      workLifeBalance: 4.2,
      compensationBenefits: 4.6,
      careerOpportunities: 4.3,
      cultureValues: 4.3,
      seniorManagement: 4.2,
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Slack_Technologies_Logo.svg/200px-Slack_Technologies_Logo.svg.png",
    },
  },
  {
    id: 28,
    name: "Shopify",
    industry: "Technology",
    headquartersCity: "Ottawa",
    headquartersState: "ON",
    sizeRange: "10000+",
    aggregateScore: {
      overallRating: 4.3,
      workLifeBalance: 4.1,
      compensationBenefits: 4.5,
      careerOpportunities: 4.3,
      cultureValues: 4.2,
      seniorManagement: 4.1,
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Shopify_logo_2018.svg/200px-Shopify_logo_2018.svg.png",
    },
  },
];

/**
 * Get demo companies for public heat map
 */
export function getDemoCompanies() {
  return DEMO_COMPANIES;
}

/**
 * Get a single demo company by ID
 */
export function getDemoCompanyById(id: number) {
  return DEMO_COMPANIES.find((c) => c.id === id);
}

/**
 * Filter demo companies based on criteria
 */
export function filterDemoCompanies(filters: {
  location?: string;
  industry?: string;
  minScore?: number;
  maxScore?: number;
}) {
  return DEMO_COMPANIES.filter((company) => {
    if (filters.location && !company.headquartersState.includes(filters.location)) {
      return false;
    }
    if (filters.industry && company.industry !== filters.industry) {
      return false;
    }
    if (
      filters.minScore &&
      (company.aggregateScore?.overallRating || 0) < filters.minScore
    ) {
      return false;
    }
    if (
      filters.maxScore &&
      (company.aggregateScore?.overallRating || 0) > filters.maxScore
    ) {
      return false;
    }
    return true;
  });
}
